import type { Experience, Skills, Project, Service, BlogPost } from '@/types';

// Static Projects Data
export const staticProjects: Project[] = [
  {
    _id: '1',
    title: 'E-commerce Platform Redesign',
    description: 'A complete overhaul of an existing e-commerce platform, focusing on user experience, performance optimization, and a modern, responsive design. Implemented new payment gateways and inventory management.',
    projectImage: '/images/E-commercePlatformRedesign.avif',
    techStack: 'Next.js, TypeScript, Tailwind CSS, Node.js, Express, MongoDB, Stripe API',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '2',
    title: 'AI-Powered Content Generator',
    description: 'Developed an intelligent web application that generates unique articles and marketing copy using advanced natural language processing models. Features include tone adjustment and keyword optimization.',
    projectImage: '/images/AI-PoweredContentGenerator.avif',
    techStack: 'Python, Flask, OpenAI API, React, Redux, PostgreSQL, Docker',
    liveDemoUrl: 'https://ai-content-generator-demo.com',
    githubUrl: 'https://github.com/yasharth/ai-content-generator',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '3',
    title: 'Interactive Personal Portfolio',
    description: 'Designed and built a highly interactive and animated personal portfolio website to showcase projects, skills, and experience. Features smooth transitions and a dark/light mode toggle.',
    projectImage: '/images/InteractivePersonalPortfolio.avif',
    techStack: 'Next.js, Framer Motion, TailwindCSS, TypeScript, Vercel',
    liveDemoUrl: 'https://yasharthsonker.vercel.app',
    githubUrl: 'https://github.com/yasharth/portfolio',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '4',
    title: 'SaaS Analytics Dashboard',
    description: 'Created a comprehensive analytics dashboard for a SaaS product, providing real-time data visualization, user behavior tracking, and customizable reporting features for business insights.',
    projectImage: '/images/SaaSAnalyticsDashboard.avif',
    techStack: 'React, Chart.js, Node.js, GraphQL, AWS Amplify, DynamoDB',
    liveDemoUrl: 'https://saas-analytics-demo.com',
    githubUrl: 'https://github.com/yasharth/saas-analytics',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '5',
    title: 'Decentralized Voting System',
    description: 'A secure and transparent voting application built on blockchain technology, ensuring immutable records and preventing fraud. Features user authentication and real-time result updates.',
    projectImage: '/images/DecentralizedVotingSystem.avif',
    techStack: 'Solidity, Ethereum, Web3.js, React, Truffle, Ganache',
    liveDemoUrl: 'https://decentralized-voting-demo.com',
    githubUrl: 'https://github.com/yasharth/blockchain-voting',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '6',
    title: 'Mobile Task Management App',
    description: 'Developed a cross-platform mobile application for efficient task management, including features like task prioritization, reminders, and collaboration. Available on iOS and Android.',
    projectImage: '/images/MobileTaskManagementApp.avif',
    techStack: 'React Native, Expo, Firebase, Redux Toolkit, Styled Components',
    liveDemoUrl: 'https://task-app-demo.com',
    githubUrl: 'https://github.com/yasharth/task-management-app',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];